apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-flask-app
  template:
    metadata:
      labels:
        app: ai-flask-app
    spec:
      containers:
      - name: ai-flask-app
        image: ai-python-app:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"