# Add Azure Container Registry (ACR) to the workflow
    
name: CI Azure Container Registry (ACR)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
  
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to ACR
      run: |
        az acr login --name ${{ secrets.ACR_NAME }}

    - name: Update registry authentication to allow pushes
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_NAME }}.azurecr.io
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Build and push image
      run: |
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/ai-python-app:v1 .
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/ai-python-app:v1

    - name: Check the image and tag
      run: |
        az acr repository list --name ${{ secrets.ACR_NAME }} --output table
        # is it "ai-python-app"?
        az acr repository show-tags --name ${{ secrets.ACR_NAME }} --repository ai-python-app --output table
        # is it "v1"?

    - name: Deploy to Azure Container Instances
      run: |
        az container create --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ai-python-app --image ${{ secrets.ACR_NAME }}.azurecr.io/ai-python-app:v1 --cpu 1 --memory 1 --registry-login-server ${{ secrets.ACR_NAME }}.azurecr.io --registry-username ${{ secrets.ACR_USERNAME }} --registry-password ${{ secrets.ACR_PASSWORD }} --ip-address Public --dns-name-label aidemo --ports 80
